blank_issues_enabled: true
contact_links:
  - name: Ask on Discord
    url: https://discord.gg/7xgjhVAg6g
    about: You can ask for help here!
  - name: Want to contribute to the step-tpm-plugin
    url: https://github.com/smallstep/step-tpm-plugin/blob/master/docs/CONTRIBUTING.md
    about: Be sure to read contributing guidelines!
